### ISSUE TITLE
Warning: Ignoring URL since it exceeds Excel's limit

### ISSUE THREAD

**Issue by hjarnek** [DominikBuchner/BOLDigger3#15]
Hi again Dominik,

After the step `Combining results with additional data and sort by input order`, I got thousands of warnings like this for different URLs:

```
/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/xlsxwriter/worksheet.py:1261: UserWarning: Ignoring URL 'https://portal.boldsystems.org/record/GBCM6651-17' since it exceeds Excel's limit of 65,530 URLS per worksheet.
  warn(
```
I would like to know what this means, and if I should do something about it. My FASTA file contains >48k records, so it's pretty large. The `*_bold_results_part_1.xlsx` output file contains 643067 rows.

Also, since BOLDigger now only yields single-sheet workbooks, I wonder whether we could have the option of just writing to plain tsv files instead? Might avoid some potential problems and unnecessary library calls that way, also downstream.

**Comment by DominikBuchner** [comment]
Hi there,
Apparently an Excel sheet can only contain 65k urls, the remaining urls are
just saved as strings, so this message can safely be ignored.

The reason I use Excel is that it is human readable and can quickly be
filtered without having to import it or something.

For downstream analysis I recommend using the parquet file that is also
returned. I moved away from saving plain text, since I don't see any
advantage. Parquet has insane read and write speed, is highly compressed so
does not use a lot of space, can be read as data frame directly for further
processing.

Joel Hjärne Kokk ***@***.***> schrieb am So., 10. Nov. 2024,
23:01:

**Comment by hjarnek** [comment]
You're right, I missed the parquet file! I agree that this is a better solution, having both options. Closing this issue.
