### ISSUE TITLE
Difference in run time between mode 1 and mode 2?

### ISSUE THREAD

**Issue by Anto007** [DominikBuchner/BOLDigger3#3]
Hi @DominikBuchner 

I was hoping if you could let me know the approx. run time in mode 1 versus mode 2 for the same set of sequences. For example, if BOLDigger3 on mode 1 finishes running in about 1 hour in the case of 10K sequences, how much time can I expect BOLDigger3 to finish running the same 10K sequences in mode 2? Thank you.

**Comment by DominikBuchner** [comment]
They should be about equal, since the queue is filled in parallel. What takes long is the additional data download. It takes ~3 minutes per 5.000 process ids. So if you switch from mode 1 to two you will have twice the amount of process IDs to query, since mode 2 return 50 hits per sequence. So expect about ~1.8 in time increase, since the ID engine should not be the bottleneck. Another factor 2 for mode three if the download starts.

e.g. I identified 10k seqs overnight in mode 3 with database 3, which is what I would recommend for the most comprehensive results. This should be acceptable.

I might need to add this to the readme: I will do some testing but I believe it should now be possible to start two instances of BOLDigger3 at the same time, e.g. identifying multiple fasta in parallel.

**Comment by Anto007** [comment]
Wow-"I identified 10k seqs overnight in mode 3 with database 3" This is what I'm looking for and I hope this works for me too. Thank you again

**Comment by DominikBuchner** [comment]
If you're really in a hurry you can also try sth like this. 

![image](https://github.com/user-attachments/assets/496b4972-039f-43a1-b8fd-41a798ba94b8)

But I'll perform some more testing here :)
